backend:
  name: git-gateway
  branch: main

media_folder: "images/projects/{{slug}}"
public_folder: "/images/projects/{{slug}}"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Project Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "PDF Documentation", name: "pdf", widget: "file" }